name: group_13_priolearn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.7
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.19.0
  molten_navigationbar_flutter: ^1.0.1
  path: ^1.9.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
